rustler::atoms! {
    ok,
    error,
    nil,
    node_stopped,
    invalid_peer_id,
    invalid_multiaddr,
    invalid_keypair,
    input_too_large,
    query_timeout,
    dht_not_enabled,
    rendezvous_not_enabled,
    internal_error,
    nif_panic,
    channel_full,
    peers_discovered,
    // Event atoms
    libp2p_event,
    libp2p_noop,
    connection_established,
    connection_closed,
    new_listen_addr,
    gossipsub_message,
    peer_discovered,
    dht_query_result,
    inbound_request,
    outbound_response,
    external_addr_confirmed,
    dial_failure,
    nat_status_changed,
    relay_reservation_accepted,
    hole_punch_outcome,
    // Endpoint atoms
    dialer,
    listener,
    // DHT result atoms
    found_record,
    not_found,
    put_record_ok,
    found_providers,
    bootstrap_ok,
    // NAT status atoms
    public,
    private,
    unknown,
    // Hole punch result atoms
    success,
    failure,
}
